import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  buildMessagingContract,
  CONVERSATION_STATUSES,
  CONVERSATION_TYPES,
  CUSTOMER_SUPPORT_TOPICS,
  SENDER_CONTEXTS,
  STORE_SUPPORT_TOPICS,
} from "./canonical-v1.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");

function stableStringify(value) {
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(",")}]`;
  if (value && typeof value === "object") {
    return `{${Object.keys(value)
      .sort()
      .map((key) => `${JSON.stringify(key)}:${stableStringify(value[key])}`)
      .join(",")}}`;
  }
  return JSON.stringify(value);
}

function write(path, content) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

const contract = buildMessagingContract();
const json = `${stableStringify(contract)}\n`;
const hash = createHash("sha256").update(json).digest("hex");

write(join(root, "generated", "messaging-contract.json"), json);

const ts = `// Generated by scripts/messaging-contract/export.mjs. Do not edit by hand.

export const MESSAGING_CONTRACT_HASH = "${hash}";
export const MESSAGING_CONTRACT_VERSION = ${contract.version} as const;

export const CONVERSATION_TYPES = ${JSON.stringify(CONVERSATION_TYPES, null, 2)} as const;
export type ConversationType = (typeof CONVERSATION_TYPES)[number];

export const CONVERSATION_STATUSES = ${JSON.stringify(CONVERSATION_STATUSES, null, 2)} as const;
export type ConversationStatus = (typeof CONVERSATION_STATUSES)[number];

export const SENDER_CONTEXTS = ${JSON.stringify(SENDER_CONTEXTS, null, 2)} as const;
export type SenderContext = (typeof SENDER_CONTEXTS)[number];

export const CUSTOMER_SUPPORT_TOPICS = ${JSON.stringify(CUSTOMER_SUPPORT_TOPICS, null, 2)} as const;
export type CustomerSupportTopic = (typeof CUSTOMER_SUPPORT_TOPICS)[number];

export const STORE_SUPPORT_TOPICS = ${JSON.stringify(STORE_SUPPORT_TOPICS, null, 2)} as const;
export type StoreSupportTopic = (typeof STORE_SUPPORT_TOPICS)[number];

export const STORE_INBOX_ACCESS = ${JSON.stringify(contract.store_inbox_access, null, 2)} as const;
export const SUPPORT_ACCESS = ${JSON.stringify(contract.support_access, null, 2)} as const;
export const LEGACY_BEHAVIOR = ${JSON.stringify(contract.legacy_behavior, null, 2)} as const;
export const ROLLOUT_PHASES = ${JSON.stringify(contract.rollout_phases, null, 2)} as const;

export type ConversationSummary = {
  id: string;
  conversation_type: ConversationType;
  status: ConversationStatus;
  listing_id: string | null;
  customer_user_id: string | null;
  store_id: string | null;
  subject: string | null;
  support_topic: CustomerSupportTopic | StoreSupportTopic | null;
  last_message_at: string | null;
  updated_at: string;
};

export type ConversationMessage = {
  id: string;
  conversation_id: string;
  sender_id: string;
  sender_context: SenderContext;
  body: string;
  created_at: string;
  metadata: Record<string, unknown>;
};

export type ConversationReadState = {
  conversation_id: string;
  user_id: string;
  last_read_message_id: string | null;
  last_read_at: string;
  archived_at: string | null;
  muted_at: string | null;
};

export function isConversationType(value: string): value is ConversationType {
  return CONVERSATION_TYPES.includes(value as ConversationType);
}

export function isConversationStatus(value: string): value is ConversationStatus {
  return CONVERSATION_STATUSES.includes(value as ConversationStatus);
}

export function isSenderContext(value: string): value is SenderContext {
  return SENDER_CONTEXTS.includes(value as SenderContext);
}
`;

write(join(root, "src", "lib", "messaging-contract", "contract.ts"), ts);

console.log(`messaging_contract_hash=${hash}`);
