// Generated by scripts/messaging-contract/export.mjs. Do not edit by hand.

export const MESSAGING_CONTRACT_HASH = "4412dcf286b36b6253a6f087745d1c421ab1533d1d4a2bdde10e8f77e5685b84";
export const MESSAGING_CONTRACT_VERSION = 1 as const;

export const CONVERSATION_TYPES = [
  "legacy_user_user",
  "customer_store",
  "customer_support",
  "store_support"
] as const;
export type ConversationType = (typeof CONVERSATION_TYPES)[number];

export const CONVERSATION_STATUSES = [
  "open",
  "waiting_customer",
  "waiting_store",
  "waiting_support",
  "resolved",
  "closed"
] as const;
export type ConversationStatus = (typeof CONVERSATION_STATUSES)[number];

export const SENDER_CONTEXTS = [
  "customer",
  "store",
  "support",
  "legacy_user"
] as const;
export type SenderContext = (typeof SENDER_CONTEXTS)[number];

export const CUSTOMER_SUPPORT_TOPICS = [
  "account",
  "store_or_product_complaint",
  "incorrect_price",
  "technical_problem",
  "other"
] as const;
export type CustomerSupportTopic = (typeof CUSTOMER_SUPPORT_TOPICS)[number];

export const STORE_SUPPORT_TOPICS = [
  "claim",
  "product_import",
  "subscription",
  "moderation",
  "store_information",
  "technical_problem",
  "other"
] as const;
export type StoreSupportTopic = (typeof STORE_SUPPORT_TOPICS)[number];

export const STORE_INBOX_ACCESS = {
  "read": [
    "owner",
    "manager",
    "staff"
  ],
  "reply": [
    "owner",
    "manager",
    "staff"
  ],
  "support": [
    "owner",
    "manager",
    "staff"
  ],
  "close": [
    "owner",
    "manager"
  ]
} as const;
export const SUPPORT_ACCESS = {
  "roles": [
    "admin",
    "moderator"
  ],
  "customerStoreAccess": [
    "reported",
    "escalated",
    "moderation",
    "legal",
    "security"
  ]
} as const;
export const LEGACY_BEHAVIOR = {
  "type": "legacy_user_user",
  "readable": true,
  "writableDuringFoundation": true,
  "writableAfterCutover": false,
  "newConversationCreationAllowedDuringFoundation": true,
  "newConversationCreationAllowedAfterEnforcement": false
} as const;
export const ROLLOUT_PHASES = {
  "foundation": "additive compatibility; existing direct legacy writes remain temporarily allowed",
  "frontend_cutover": "web and mobile switch to RPC creation and message sending",
  "enforcement": "direct conversation/message inserts are blocked; legacy history remains readable"
} as const;

export type ConversationSummary = {
  id: string;
  conversation_type: ConversationType;
  status: ConversationStatus;
  listing_id: string | null;
  customer_user_id: string | null;
  store_id: string | null;
  subject: string | null;
  support_topic: CustomerSupportTopic | StoreSupportTopic | null;
  last_message_at: string | null;
  updated_at: string;
};

export type ConversationMessage = {
  id: string;
  conversation_id: string;
  sender_id: string;
  sender_context: SenderContext;
  body: string;
  created_at: string;
  metadata: Record<string, unknown>;
};

export type ConversationReadState = {
  conversation_id: string;
  user_id: string;
  last_read_message_id: string | null;
  last_read_at: string;
  archived_at: string | null;
  muted_at: string | null;
};

export function isConversationType(value: string): value is ConversationType {
  return CONVERSATION_TYPES.includes(value as ConversationType);
}

export function isConversationStatus(value: string): value is ConversationStatus {
  return CONVERSATION_STATUSES.includes(value as ConversationStatus);
}

export function isSenderContext(value: string): value is SenderContext {
  return SENDER_CONTEXTS.includes(value as SenderContext);
}
