-- Shared search vocabulary for web and mobile

create table if not exists public.search_vocabulary (
  id bigint generated by default as identity primary key,
  raw_term text not null,
  normalized_term text not null,
  script_type text,
  language text,
  canonical_key text,
  source text not null default 'tap_suggestions',
  review_status text not null default 'unreviewed',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists search_vocabulary_source_raw_term_idx
  on public.search_vocabulary (source, raw_term);

create index if not exists search_vocabulary_normalized_term_idx
  on public.search_vocabulary (normalized_term);

create index if not exists search_vocabulary_canonical_key_idx
  on public.search_vocabulary (canonical_key)
  where canonical_key is not null;

alter table public.search_vocabulary enable row level security;
revoke all on table public.search_vocabulary
  from public, anon, authenticated;

revoke all on sequence public.search_vocabulary_id_seq
  from public, anon, authenticated;

grant all on table public.search_vocabulary
  to service_role;

grant usage, select on sequence public.search_vocabulary_id_seq
  to service_role;
